# Generated by Django 5.0.2 on 2024-03-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_profile_user_delete_contact_delete_library_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default=0, max_length=254),
        ),
    ]
